### PR TITLE
Serialize directly to string

### LINKED ISSUE #26: serde implementation does not work round-trip
The derived `Serialize` implementation serializes the email as a `newtype_struct` containing a `string`, but the manual `Deserialize` implementation expects only a `string`. This causes deserializing a previously serialized value to fail when using any serde format that does not bypass the `newtype_struct`, such as [`ron`](https://github.com/ron-rs/ron). For example, here we can see the error occur:

``` rust
use email_address::EmailAddress;

let email = EmailAddress::from_str("user.name+tag+sorting@example.com").expect("couldn't parse email");

let serialized = ron::to_string(&email).expect("couldn't serialize email");
let deserialized: EmailAddress = ron::from_str(&serialized).expect("couldn't deserialize email");
```

This code panics when attempting to deserialize.

In general, the correct thing to do with generic serde implementations is to use the same [data model](https://serde.rs/data-model.html) in both serialization and deserialization.

### PR DESCRIPTION
**Pull request by Anders429**
Fixes #26.

This simply provides a manual implementation of `Serialize` that correctly round-trips with the already-existing `Deserialize` implementation.

I also provided tests for both the failing round-trip (the test fails before the fix, and passes after), as well as a few other `serde`-related tests. With those tests I added `dev-dependencies` on both [`serde_assert`](https://github.com/Anders429/serde_assert) (for testing the serde implementations) and [`claims`](https://github.com/mattwilkinsonn/rust-claims) (for making assertions with `Result` types much more ergonomic).

Note that this is a breaking change.

### CODE REVIEW

File: src/lib.rs [hunk 1]
```diff
@@ -1109,4 +1121,68 @@ mod tests {
...
+            EmailAddress::deserialize(&mut deserializer),
+            serde_assert::de::Error::invalid_type(
+                Unexpected::Unsigned(42),
+                &"string containing a valid email address"
+            )
+        );
+    }
+
+    #[cfg(feature = "serde_support")]
+    #[test]
```
Comment (johnstonskj) [inline src/lib.rs:1178]: Can you just add a comment here, it's nice to keep track of these things.

```
// Regression test: GitHub issue #26
```

**Review by johnstonskj — CHANGES_REQUESTED** [review]
Thanks, especially for the test case.

File: src/lib.rs (hunk 1 above)
Comment (Anders429) [reply src/lib.rs:1179]: Good idea, I added the comment!
